[settings]
PORT = 443
MAX_CLIENTS = 5000
CERT_KEY_DIR = 'certs/cert.pem'
TLS_KEY_DIR = 'certs/cert.key.pem'
TCP_LISTENER_ADDRESS = '127.0.0.1'
IP_CONNECTION_LIMIT = 20
CONNECTION_TIMEOUT = 120
KEEP_ALIVE_TIMEOUT = 15
PARSING_TIMEOUT = 30
REQUEST_SIZE_LIMIT = 8388608
HEADER_SIZE_LIMIT = 32768